### ISSUE TITLE
Building without umbrella project

### ISSUE THREAD

**Issue by elvanja** [videlalvaro/rabbitmq-recent-history-exchange-elixir#1]
Hi @videlalvaro, thanks for the writeup and this sample project!

I'm trying to build a custom authentication plugin for RabbitMQ, based on these instructions: https://github.com/rabbitmq/rabbitmq-auth-backend-http and would like to do it with Elixir, hence the reference to your article :)

Anyway, the http://www.rabbitmq.com/plugin-development.html no longer mention the umbrella project. In fact, https://github.com/rabbitmq/rabbitmq-public-umbrella states that since 3.6.0 it is no longer needed for working on an individual plugin.

So, I was wondering if there is a way to build this project using the new erlang.mk style?

I tried it, but for example, can't declare `elixir` or `elixir-wrapper` in `DEPS` section at `Makefile`. Not sure how to proceed.

Thank you!

**Comment by videlalvaro** [comment]
AFAIK plugins use erlang.mk ping @dumbbell

**Comment by elvanja** [comment]
@videlalvaro thanks for the info :)
